const SITELIST = [
  { url: "http://www.duzcetv.com/", city: "81" },
  { url: "http://www.oxijen.tv/", city: "81" },
  { url: "http://www.duzcepostasi.com/", city: "81" },
  { url: "http://www.duzceninsesi.com.tr/", city: "81" },
  { url: "http://www.duzceparantez.com/", city: "81" },
  { url: "http://www.gunaydinduzce.com/", city: "81" },
  { url: "http://www.maviduzce.com/", city: "81" },
  { url: "http://www.burasiduzce.com/", city: "81" },
  { url: "http://www.duzcerota.com/", city: "81" },
  { url: "http://www.duzcesonhaber.com/", city: "81" },
  { url: "http://duzceyerelhaber.com/", city: "81" },
  { url: "http://akcakocatv.com/", city: "81" },
  { url: "http://duzcedetay.com/", city: "81" },
  { url: "http://duzceobjektif.com/", city: "81" },
  { url: "http://www.duzcemanset.com.tr/", city: "81" },
  { url: "http://www.oncurtv.com/", city: "81" },
  { url: "http://www.81oraytv.com/", city: "81" },
  { url: "http://www.duzcedamla.com/", city: "81" },
  { url: "http://www.duzcearti.com/", city: "81" },
  { url: "http://duzcetakip.com/", city: "81" },
  { url: "https://haberozel.com.tr/", city: "81" },
  { url: "http://www.duzcelife.com/", city: "81" },
  { url: "http://www.duzcehavadis.net/", city: "81" },
  { url: "http://www.duzcepusula.com/", city: "81" },
  { url: "http://www.memleketimduzce.com/", city: "81" },
  { url: "http://www.malumathaber.com/", city: "81" },
  { url: "http://www.habergercek.org/", city: "81" },
  { url: "http://www.haberolduk.com/", city: "81" },
  { url: "http://www.duzcehurhaber.com/", city: "81" },
  { url: "http://www.duzcedebugun.com/", city: "81" },
  { url: "http://www.duzceanaliz.com/", city: "81" },
  { url: "http://duzcekent.com/", city: "81" },
  { url: "http://haber380.com/", city: "81" },
  { url: "http://www.akcakocapostasi.com/", city: "81" },
  { url: "http://akcakocahavadis.com/", city: "81" },
  { url: "http://www.yeniakcakocahaber.com/", city: "81" },
  { url: "http://www.yigilcaninsesi.net/", city: "81" },
  { url: "http://www.cagdasgumusova.com/", city: "81" },
  { url: "https://www.81duzcehaber.com/", city: "81" },
  { url: "https://www.bizimduzce.com/", city: "81" },
  { url: "http://duzcehaber.com/", city: "81" },
  { url: "http://www.merkeztv.com.tr/", city: "14" },
  { url: "http://www.bizbolulular.com/", city: "14" },
  { url: "https://www.koroglugazetesi.com/", city: "14" },
  { url: "http://www.ozgurbolu.com/", city: "14" },
  { url: "https://bolugazetesi.com.tr/", city: "14" },
  { url: "http://www.bolugundem.com/", city: "14" },
  { url: "https://www.sondakikabolu.com/", city: "14" },
  { url: "http://www.bolutakip.com/", city: "14" },
  { url: "https://www.bolununsesi.com/", city: "14" },
  { url: "http://www.boluolay.com/", city: "14" },
  { url: "https://boluhavadis.net/", city: "14" },
  { url: "http://boluekspres.com/", city: "14" },
  { url: "http://www.bolu724.net/", city: "14" },
  { url: "https://www.memleketimbolu.com/", city: "14" },
  { url: "https://bolubakishaber.com/", city: "14" },
  { url: "https://boluyankihaber.com/", city: "14" },
  { url: "http://www.geredemedyatakip.com.tr/", city: "14" },
  { url: "https://www.boluhedef.com/", city: "14" },
  { url: "https://boluobjektif.com/", city: "14" },
  { url: "http://www.geredeyenigun.com/", city: "14" },
  { url: "https://www.boludabolu.com/", city: "14" },
  { url: "http://www.bolusporluyuz.com/", city: "14" },
  { url: "http://www.futbolumuz.com/", city: "14" },
  { url: "https://www.haber14.com/", city: "14" },
  { url: "http://www.boluradikal.com/", city: "14" },
  { url: "https://mengen.gen.tr/", city: "14" },
  { url: "http://dortdivandunyasi.com/", city: "14" },
  { url: "http://bolununhaberi.com/", city: "14" },
  { url: "https://www.surmansetbolu.com/", city: "14" },
  { url: "http://www.mudurnuhaber.com/", city: "14" },
  { url: "http://www.mercanmedya.com/", city: "14" },
  { url: "https://bolukoroglu.com/", city: "14" },
  { url: "https://www.bolumeydan.com", city: "14" },
  { url: "http://www.boluanahaber.com", city: "14" },
  { url: "https://vizyonbolu.com/", city: "14" },
  { url: "https://interbolutv.com/", city: "14" },
  { url: "http://www.gazetebolu.com/", city: "14" },
  { url: "https://www.tvbolu.com.tr/", city: "14" },
  { url: "https://www.boluobjektif.com/", city: "14" },
  { url: "https://www.bolukenthaber.com/", city: "14" },
  { url: "http://www.gercekbolu.com/", city: "14" },
  { url: "http://bolusondakikahaber.com/", city: "14" },
  { url: "https://www.bolusonhaber.com/", city: "14" },
  { url: "http://www.medya14.net/", city: "14" },
  { url: "https://www.spor14.com/", city: "14" },
  { url: "http://www.kastamonugazetesi.com.tr/", city: "37" },
  { url: "http://www.aciksoz.com.tr/", city: "37" },
  { url: "http://www.inebolupostasi.com/", city: "37" },
  { url: "https://tosyahaber37.com/", city: "37" },
  { url: "http://www.kastamonugundemgazetesi.com/", city: "37" },
  { url: "http://istamonu.com/", city: "37" },
  { url: "https://dogrusozgazetesi.com/", city: "37" },
  { url: "http://www.bozkurtgundem.com/", city: "37" },
  { url: "http://www.inebolugazetesi.com/", city: "37" },
  { url: "https://www.kastamonuguncel.com/", city: "37" },
  { url: "https://www.kastamonuilkhaber.com/", city: "37" },
  { url: "https://www.tosyahaberleri.com/", city: "37" },
  { url: "https://www.kurebulten.com/", city: "37" },
  { url: "http://www.cide.gen.tr/", city: "37" },
  { url: "http://www.kastamonubirincihaber.com/", city: "37" },
  { url: "http://www.vitrinhaber.com/", city: "57" },
  { url: "http://www.boyabatgazetesi.com/", city: "57" },
  { url: "https://www.boyabatsesi.com/", city: "57" },
  { url: "https://www.ayancikgazetesi.com/", city: "57" },
  { url: "http://www.haber57.com.tr/", city: "57" },
  { url: "https://www.ajanssinop.com/", city: "57" },
  { url: "http://www.turkelihaber.com/", city: "57" },
  { url: "http://www.boyabatgundem.net/", city: "57" },
  { url: "https://www.ayancikdogus.com/", city: "57" },
  { url: "http://www.sinoppusulasi.com.tr/", city: "57" },
  { url: "http://bizimkaradeniz.com.tr/", city: "57" },
  { url: "http://www.sinopflashaber.com/", city: "57" },
  { url: "http://www.turkelihaber.com/", city: "57" },
  { url: "https://www.gerzeninsesi.com/0", city: "57" },
  { url: "https://boyabat.com/", city: "57" },
  { url: "https://www.duragan.com/", city: "57" },
  { url: "http://www.gerzegundemhaber.com/", city: "57" },
  { url: "https://www.boyabatsonhaber.com/", city: "57" },
  { url: "http://karabukmeydanhaber.com/", city: "78" },
  { url: "https://www.karabukhaber.com.tr/", city: "78" },
  { url: "https://www.karabukpostasi.com/", city: "78" },
  { url: "http://www.safranbolusonsoz.com/", city: "78" },
  { url: "http://bolgeninsesigazetesi.com/", city: "78" },
  { url: "http://www.safranboludasonsoz.com/", city: "78" },
  { url: "http://www.batikaradenizekspresgazetesi.com.tr/index.html", city: "78" },
  { url: "http://www.karabuknethaber.com/", city: "78" },
  { url: "https://www.brtv.com.tr/", city: "78" },
  { url: "https://www.karabukderinhaber.com/", city: "78" },
  { url: "https://karabukgundem.com/", city: "78" },
  { url: "https://www.kardemirkarabukspor.org.tr/", city: "78" },
  { url: "https://www.karabukajans78.com/", city: "78" },
  { url: "https://www.karabukanahaber.com/", city: "78" },
  { url: "https://www.ozgurkocaeli.com.tr/", city: "41" },
  { url: "https://www.kocaeligazetesi.com.tr/", city: "41" },
  { url: "https://www.cagdaskocaeli.com.tr/", city: "41" },  
  { url: "https://demokratkocaeli.com/", city: "41" },
  { url: "https://www.hedefgazetesi.com.tr/", city: "41" },
  { url: "https://www.marmaragazetesi.com/", city: "41" },
  { url: "https://www.gebzeyenigun.com/", city: "41" },
  { url: "https://www.ozgunkocaeli.com.tr/", city: "41" },
  { url: "http://www.yakintakipgazetesi.com/", city: "41" },
  { url: "https://www.kartepegazetesi.com.tr/", city: "41" },
  { url: "https://www.bizimyaka.com/", city: "41" },
  { url: "https://www.kocaelipusula.com/", city: "41" },
  { url: "https://www.yenigolcuk.com/", city: "41" },
  { url: "http://www.bizimgazete.com.tr/", city: "41" },
  { url: "http://www.nefesgazetesi.com/", city: "41" },
  { url: "https://kocaelihaberdunyasi.com/", city: "41" },
  { url: "http://onursalhaber.com.tr/", city: "41" },
  { url: "https://www.mavikocaeli.com.tr/", city: "41" },
  { url: "http://www.41havadis.com/", city: "41" },
  { url: "http://www.golcukpostasi.com/", city: "41" },
  { url: "https://www.kandiraninsesi.com/", city: "41" },
  { url: "https://www.gebzehaber.net/", city: "41" },
  { url: "http://www.kocaelioncu.com/", city: "41" },
  { url: "http://www.gebzegazetesi.com/", city: "41" },
  { url: "https://golcukhaber.com.tr/", city: "41" },
  { url: "http://www.yenibolgegazetesi.com/", city: "41" },
  { url: "https://www.millihakimiyet.com/", city: "41" },
  { url: "https://www.daricagazetesi.com.tr/", city: "41" },
  { url: "https://www.kulishaber.com.tr/", city: "41" },
  { url: "https://www.buyukkocaeli.com.tr/", city: "41" },
  { url: "http://www.golgegazetesi.com/", city: "41" },
  { url: "http://www.kocaelimeydan.com/", city: "41" },
  { url: "https://golcukvizyongazetesi.com/", city: "41" },
  { url: "http://www.mansetmarmara.com/anasayfa", city: "41" },
  { url: "http://www.kocaelisanayigazetesi.com/", city: "41" },
  { url: "https://finanskocaeli.com/", city: "41" },
  { url: "https://www.gundemkocaeli.com.tr/", city: "41" },
  { url: "https://www.korfezgazetesi.com.tr/", city: "41" },
  { url: "http://www.sozkocaeli.com/", city: "41" },
  { url: "http://www.yenigebze.com/", city: "41" },
  { url: "http://www.derinceekspres.org/", city: "41" },
  { url: "https://www.korfezmanset.com/", city: "41" },
  { url: "https://www.kirkbir.com/", city: "41" },
  { url: "https://www.bizimdarica.com/", city: "41" },
  { url: "http://www.karamurselaktifhaber.com/", city: "41" },
  { url: "http://www.degisenkocaeli.com/", city: "41" },
  { url: "http://kocaelisonnokta.com/", city: "41" },
  { url: "https://www.haberkaramursel.net/", city: "41" },
  { url: "https://www.marmaramanset.com/", city: "41" },
  { url: "https://www.haberkartepe.com/", city: "41" },
  { url: "https://www.kocaelikoz.com/", city: "41" },
  { url: "https://www.kocaelidenge.com/", city: "41" },
  { url: "https://www.enkocaeli.com/", city: "41" },
  { url: "https://www.kocaelibarisgazetesi.com/", city: "41" },
  { url: "https://www.bagimsizkocaeli.com.tr/", city: "41" },
  { url: "https://www.istekocaeli.com/", city: "41" },
  { url: "https://www.bugunkocaeli.com.tr/", city: "41" },
  { url: "http://www.astakoshaber.com/", city: "41" },
  { url: "https://kocaelifikir.com/", city: "41" },
  { url: "https://www.kocaelihalkgazetesi.com/", city: "41" },
  { url: "https://www.haberpi.com/", city: "41" },
  { url: "https://www.tekkocaeli.com/", city: "41" },
  { url: "https://www.gazetegebze.com.tr/", city: "41" },
  { url: "https://www.golcukgundem.com/", city: "41" },
  { url: "https://kocaelihaberdunyasi.com/", city: "41" },
  { url: "https://karamursel.tv/", city: "41" },
  { url: "http://www.kocaelihaberci.com/", city: "41" },
  { url: "https://www.t4haber.com/", city: "41" },
  { url: "https://www.kocaeliparaf.com/", city: "41" },
  { url: "http://www.korkusuzkocaeli.com/", city: "41" },
  { url: "http://www.kocaeliburada.com/", city: "41" },
  { url: "https://www.kocaelitv.com.tr/", city: "41" },
  { url: "https://www.7x24kocaeli.com/", city: "41" },
  { url: "http://www.dokuzhaber.com/", city: "41" },
  { url: "http://www.gebzehaberler.com/", city: "41" },
  { url: "http://www.gebzeninsesi.com/", city: "41" },
  { url: "http://www.kocaeliokur.com/", city: "41" },
  { url: "http://izmitpusula.com/", city: "41" },
  { url: "https://www.sizinkocaeli.com/", city: "41" },
  { url: "http://netkocaeli.com/", city: "41" },
  { url: "https://www.golcuk.com.tr/", city: "41" },
  { url: "https://www.izmitcity.com/", city: "41" },
  { url: "https://basiskelede.com/", city: "41" },
  { url: "http://www.belirtiyorum.com/", city: "41" },
  { url: "https://www.flaskocaeli.com/", city: "41" },
  { url: "http://www.kandiralilar.com/", city: "41" },
  { url: "https://derinceninsesi.com/", city: "41" },
  { url: "http://www.kocaelibizimsehir.com/", city: "41" },
  { url: "http://www.kandirahaber.com/", city: "41" },
  { url: "https://sekahaber.net/", city: "41" },
  { url: "http://pusulamarmara.com/", city: "41" },
  { url: "http://golcukobjektif.com/", city: "41" },
  { url: "http://www.kocaeliekspres.net/", city: "41" },
  { url: "https://www.kandiraburada.com/", city: "41" },
  { url: "http://41medya.com/", city: "41" },
  { url: "https://starkocaeli.com/", city: "41" },
  { url: "http://www.batiyakasitv.com.tr/", city: "41" },
  { url: "https://www.kocaelitv.com.tr/", city: "41" },
  { url: "http://tv41.com.tr/", city: "41" },  
  { url: "https://www.sakaryayenihaber.com/", city: "54" },
  { url: "http://www.bizimsakarya.com.tr/", city: "54" },
  { url: "https://www.aksamhaberleri.com.tr/", city: "54" },
  { url: "https://www.yenisakarya.com/", city: "54" },
  { url: "http://www.karasuhaber.com/", city: "54" },
  { url: "https://www.bizimhendek.com/", city: "54" },
  { url: "https://www.bombagazete.com/", city: "54" },
  { url: "https://www.sakaryayenigun.com.tr/", city: "54" },
  { url: "http://www.e-sakarya.net/", city: "54" },
  { url: "http://www.kaynarcahaber.com/", city: "54" },
  { url: "http://www.adapostasi.com/", city: "54" },
  { url: "https://www.sakaryakuzey.com/", city: "54" },
  { url: "https://medyabar.com/", city: "54" },
  { url: "https://t54.com.tr/", city: "54" },
  { url: "https://www.halk54.com/", city: "54" },
  { url: "https://www.haberlisin.com/", city: "54" },
  { url: "https://www.haber54.com.tr/", city: "54" },
  { url: "https://www.adayorum.com/", city: "54" },
  { url: "https://www.sakaryayerelhaber.com/", city: "54" },
  { url: "https://www.sakaryadanhaber.com/", city: "54" },
  { url: "https://spor264.com.tr/", city: "54" },
  { url: "https://www.hendekgundem.com/", city: "54" },
  { url: "https://www.sporexpres.com/", city: "54" },
  { url: "https://www.adatavir.com/", city: "54" },
  { url: "https://www.pamukovahalk.com/", city: "54" },
  { url: "https://www.akyazihaber.com/", city: "54" },
  { url: "https://sakarya360.com/", city: "54" },
  { url: "https://www.hendekhaber.com.tr/", city: "54" },
  { url: "https://www.karasuhaberleri.com/", city: "54" },
  { url: "http://www.haberhendek.com/", city: "54" },
  { url: "http://www.medyayazar.com/", city: "54" },
  { url: "https://www.sapanca.com.tr/", city: "54" },
  { url: "https://www.sakarya24haber.com/", city: "54" },
  { url: "https://www.netgaste.com/", city: "54" },
  { url: "https://www.sakaryahaber.com/", city: "54" },
  { url: "https://sakaryadetayhaber.com/", city: "54" },
  { url: "https://www.gozlemsakarya.com/", city: "54" },
  { url: "https://geyvemedya.com/", city: "54" },
  { url: "https://www.sakaryarehberim.com/", city: "54" },
  { url: "https://www.akyazi.net/", city: "54" },
  { url: "https://www.canses.net/", city: "54" },
  { url: "https://www.taraklimedya.com/", city: "54" },
  { url: "https://www.mihraphaber.com/", city: "54" },
  { url: "http://www.tarakliajans.com/", city: "54" },
  { url: "http://www.geyvehaber.com/", city: "54" },
  { url: "https://www.sakaryaspor.com.tr/", city: "54" },
  { url: "https://www.akyazihavadis.com/", city: "54" },
  { url: "https://www.kislacay.com/", city: "54" },
  { url: "https://www.kocaali.com/", city: "54" },
  { url: "http://www.bizimakyazi.com/", city: "54" },
  { url: "https://www.akyazihalkinsesi.com/", city: "54" },
  { url: "https://www.haberdibimde.com/", city: "54" },
  { url: "https://www.sakaryamedyasi.com/", city: "54" },
  { url: "https://www.adahaber54.com/", city: "54" },
  { url: "https://www.sakaryaanaliz.com.tr/", city: "54" },
  { url: "https://www.basin54.com/", city: "54" },
  { url: "https://www.sakaryamedyahaber.com/", city: "54" },
  { url: "https://www.adapazarinet.com/", city: "54" },
  { url: "http://adamanset.net/", city: "54" },
  { url: "https://www.tv264.com.tr/", city: "54" },
  { url: "http://www.degisimmedya.com/", city: "67" },
  { url: "http://www.inanisgazetesi.com/", city: "67" },
  { url: "http://www.yeniufuk.com.tr/", city: "67" },
  { url: "http://www.halkinsesi.com.tr/", city: "67" },
  { url: "http://www.ereglidemokratmedya.com/", city: "67" },
  { url: "http://www.yeniadimgazetesi.com/", city: "67" },
  { url: "http://www.ereglionder.com.tr/", city: "67" },
  { url: "https://www.gundem67.com/", city: "67" },
  { url: "http://www.kdzereglihaber.com/", city: "67" },
  { url: "https://www.safakgazete.com/index.php", city: "67" },
  { url: "http://www.ereglihakimiyet.com/", city: "67" },
  { url: "http://www.bolgehaber67.net/", city: "67" },
  { url: "http://www.caycuma.org/", city: "67" },
  { url: "http://www.sonhaberimiz.com/", city: "67" },
  { url: "http://www.damar67.com/", city: "67" },
  { url: "http://www.eregliyankihaber.com/", city: "67" },
  { url: "http://www.eregliyenihaber.com/", city: "67" },
  { url: "http://www.sirineregli.org/", city: "67" },
  { url: "https://www.halkinnabzi.net/", city: "67" },
  { url: "http://www.kdzmeydangazetesi.com/", city: "67" },
  { url: "http://www.batikaradenizhaber.com/", city: "67" },
  { url: "https://yenizonguldak.com/", city: "67" },
  { url: "https://www.imzagazetesi.com.tr/", city: "67" },
  { url: "http://www.halkpostasi.com/", city: "67" },
  { url: "https://67mercekgazetesi.com/", city: "67" },
  { url: "http://www.arayisgazetesi.net/", city: "67" },
  { url: "https://www.zhaber.com.tr/", city: "67" },
  { url: "http://www.kariyermedya.net/", city: "67" },
  { url: "https://www.kanal67.com.tr/", city: "67" },
  { url: "http://www.ereglibulteni.com/", city: "67" },
  { url: "http://www.yeniadimgazetesi.com/", city: "67" },
  { url: "https://www.kanal67.com.tr/", city: "67" },
  { url: "http://www.kanalz.com.tr/", city: "67" },
  { url: "http://www.pusula67.com.tr/", city: "67" },
  { url: "https://bartinolay.com/", city: "74" },
  { url: "https://bartinhergungazetesi.com/", city: "74" },
  { url: "http://www.bartinhalkgazetesi.com.tr/", city: "74" },
  { url: "http://www.bartinmanset.com/", city: "74" },
  { url: "http://www.bartinpusula.com.tr/", city: "74" },
  { url: "https://www.bartin.info/", city: "74" },
  { url: "http://www.bartintv.com.tr/", city: "74" },
  { url: "https://bartinhaber74.com/", city: "74" },
  { url: "http://bartintv.com.tr/", city: "74" },
  { url: "https://www.medyajans.com/", city: "0" },
  { url: "http://superhaber.tv/", city: "0" },
  { url: "http://www.haber7.com/", city: "0" },
  { url: "http://www.trthaber.com/", city: "0" },
  { url: "https://www.ntv.com.tr/", city: "0" },
  { url: "http://www.aa.com.tr/", city: "0" },
  { url: "http://www.cnnturk.com/", city: "0" },
  { url: "http://ensonhaber.com/", city: "0" },
  { url: "https://www.haberturk.com/", city: "0" },
  { url: "http://www.iha.com.tr/", city: "0" },
  { url: "http://www.haberler.com/", city: "0" },
  { url: "http://www.ahaber.com.tr/", city: "0" },
  { url: "http://www.internethaber.com/", city: "0" },
  { url: "http://www.dha.com.tr/", city: "0" },
  { url: "https://veryansintv.com/", city: "0" },
  { url: "https://www.bbc.com/turkce", city: "0" },
  { url: "http://www.diken.com.tr/", city: "0" },
  { url: "https://tr.sputniknews.com/", city: "0" },
  { url: "http://www.t24.com.tr/", city: "0" },
  { url: "https://www.amerikaninsesi.com/", city: "0" },
  { url: "http://www.gercekgundem.com/", city: "0" },
  { url: "https://tr.euronews.com/", city: "0" },
  { url: "http://www.f5haber.com/", city: "0" },
  { url: "https://www.dw.com/", city: "0" },
  { url: "http://www.beyazgazete.com/", city: "0" },
  { url: "https://indyturk.com/", city: "0" },
  { url: "http://www.memurlar.net/", city: "0" },
  { url: "http://www.gazetevatan.com/", city: "0" },
  { url: "http://www.haber3.com/", city: "0" },
  { url: "http://www.stargazete.com/", city: "0" },
  { url: "https://www.sondakika.com/", city: "0" },
  { url: "http://www.medyafaresi.com/", city: "0" },
  { url: "https://medyascope.tv/", city: "0" },
  { url: "https://www.mynet.com/", city: "0" },
  { url: "http://www.turktime.com/", city: "0" },
  { url: "http://www.hurhaber.com/", city: "0" },
  { url: "http://www.objektifhaber.com/", city: "0" },
  { url: "http://www.habervakti.com/", city: "0" },
  { url: "http://www.eurovizyon.co.uk/", city: "0" },
  { url: "http://www.habervitrini.com/", city: "0" },
  { url: "http://www.bigpara.com/", city: "0" },
  { url: "http://www.tgrthaber.com.tr/", city: "0" },
  { url: "http://www.pressturk.com/", city: "0" },
  { url: "http://www.timeturk.com/", city: "0" },
  { url: "http://www.netgazete.com/", city: "0" },
];

const CITIES = {
  0: { plate: 0, name: "ULUSAL" },
  1: { plate: 1, name: "ADANA" },
  2: { plate: 2, name: "ADIYAMAN" },
  3: { plate: 3, name: "AFYONKARAHİSAR" },
  4: { plate: 4, name: "AĞRI" },
  5: { plate: 5, name: "AMASYA" },
  6: { plate: 6, name: "ANKARA" },
  7: { plate: 7, name: "ANTALYA" },
  8: { plate: 8, name: "ARTVİN" },
  9: { plate: 9, name: "AYDIN" },
  10: { plate: 10, name: "BALIKESİR" },
  11: { plate: 11, name: "BİLECİK" },
  12: { plate: 12, name: "BİNGÖL" },
  13: { plate: 13, name: "BİTLİS" },
  14: { plate: 14, name: "BOLU" },
  15: { plate: 15, name: "BURDUR" },
  16: { plate: 16, name: "BURSA" },
  17: { plate: 17, name: "ÇANAKKALE" },
  18: { plate: 18, name: "ÇANKIRI" },
  19: { plate: 19, name: "ÇORUM" },
  20: { plate: 20, name: "DENİZLİ" },
  21: { plate: 21, name: "DİYARBAKIR" },
  22: { plate: 22, name: "EDİRNE" },
  23: { plate: 23, name: "ELAZIĞ" },
  24: { plate: 24, name: "ERZİNCAN" },
  25: { plate: 25, name: "ERZURUM" },
  26: { plate: 26, name: "ESKİŞEHİR" },
  27: { plate: 27, name: "GAZİANTEP" },
  28: { plate: 28, name: "GİRESUN" },
  29: { plate: 29, name: "GÜMÜŞHANE" },
  30: { plate: 30, name: "HAKKARİ" },
  31: { plate: 31, name: "HATAY" },
  32: { plate: 32, name: "ISPARTA" },
  33: { plate: 33, name: "MERSİN(İÇEL)" },
  34: { plate: 34, name: "İSTANBUL" },
  35: { plate: 35, name: "İZMİR" },
  36: { plate: 36, name: "KARS" },
  37: { plate: 37, name: "KASTAMONU" },
  38: { plate: 38, name: "KAYSERİ" },
  39: { plate: 39, name: "KIRKLARELİ" },
  40: { plate: 40, name: "KIRŞEHİR" },
  41: { plate: 41, name: "KOCAELİ" },
  42: { plate: 42, name: "KONYA" },
  43: { plate: 43, name: "KÜTAHYA" },
  44: { plate: 44, name: "MALATYA" },
  45: { plate: 45, name: "MANİSA" },
  46: { plate: 46, name: "KAHRAMANMARAŞ" },
  47: { plate: 47, name: "MARDİN" },
  48: { plate: 48, name: "MUĞLA" },
  49: { plate: 49, name: "MUŞ" },
  50: { plate: 50, name: "NEVŞEHİR" },
  51: { plate: 51, name: "NİĞDE" },
  52: { plate: 52, name: "ORDU" },
  53: { plate: 53, name: "RİZE" },
  54: { plate: 54, name: "SAKARYA" },
  55: { plate: 55, name: "SAMSUN" },
  56: { plate: 56, name: "SİİRT" },
  57: { plate: 57, name: "SİNOP" },
  58: { plate: 58, name: "SİVAS" },
  59: { plate: 59, name: "TEKİRDAĞ" },
  60: { plate: 60, name: "TOKAT" },
  61: { plate: 61, name: "TRABZON" },
  62: { plate: 62, name: "TUNCELİ" },
  63: { plate: 63, name: "ŞANLIURFA" },
  64: { plate: 64, name: "UŞAK" },
  65: { plate: 65, name: "VAN" },
  66: { plate: 66, name: "YOZGAT" },
  67: { plate: 67, name: "ZONGULDAK" },
  68: { plate: 68, name: "AKSARAY" },
  69: { plate: 69, name: "BAYBURT" },
  70: { plate: 70, name: "KARAMAN" },
  71: { plate: 71, name: "KIRIKKALE" },
  72: { plate: 72, name: "BATMAN" },
  73: { plate: 73, name: "ŞIRNAK" },
  74: { plate: 74, name: "BARTIN" },
  75: { plate: 75, name: "ARDAHAN" },
  76: { plate: 76, name: "IĞDIR" },
  77: { plate: 77, name: "YALOVA" },
  78: { plate: 78, name: "KARABÜK" },
  79: { plate: 79, name: "KİLİS" },
  80: { plate: 80, name: "OSMANİYE" },
  81: { plate: 81, name: "DÜZCE" },
};

module.exports = { SITELIST, CITIES };
